import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{BrowserRouter,Routes,Route,Link,NavLink,useParams}from'react-router-dom';import{Shield,Dice5,ArrowLeft}from'lucide-react';import'./style.css';
const API='https://www.dnd5eapi.co/api/2014';const names=['Arthos Valem','Lyra Moonwhisper','Dorian Blackshield','Kael Stormborn','Mira Dawnblade','Tharion Duskwalker','Elora Nightbloom','Borin Ironfoot'];
async function req(e){const r=await fetch(API+e);if(!r.ok)throw Error('Erro ao buscar dados da API');return r.json()}async function list(e){return(await req(e)).results}function pick(a){return a[Math.floor(Math.random()*a.length)]}function attr(){return Math.floor(Math.random()*11)+8}
function Header(){return <header><Link className="brand" to="/"><Shield/>RPG Character Forge</Link><nav><NavLink to="/">Início</NavLink><NavLink to="/gerador">Gerador</NavLink></nav></header>}
function Home(){const[rs,setRs]=useState([]),[cs,setCs]=useState([]),[load,setLoad]=useState(true);useEffect(()=>{Promise.all([list('/races'),list('/classes')]).then(([r,c])=>{setRs(r);setCs(c);setLoad(false)})},[]);if(load)return <main className="center">Carregando API...</main>;return <main className="container"><section className="hero"><div><span>React + API + Rotas Dinâmicas</span><h1>Gerador de Personagens RPG</h1><p>Projeto usando D&D 5e API, links internos e páginas dinâmicas.</p><Link className="btn" to="/gerador"><Dice5/>Gerar personagem</Link></div></section><h2>Raças</h2><div className="grid">{rs.map(x=><Link className="card" to={'/racas/'+x.index} key={x.index}>{x.name}<small>Ver detalhes</small></Link>)}</div><h2>Classes</h2><div className="grid">{cs.map(x=><Link className="card" to={'/classes/'+x.index} key={x.index}>{x.name}<small>Ver detalhes</small></Link>)}</div></main>}
function Generator(){const[rs,setRs]=useState([]),[cs,setCs]=useState([]),[ch,setCh]=useState(null);useEffect(()=>{Promise.all([list('/races'),list('/classes')]).then(([r,c])=>{setRs(r);setCs(c);gen(r,c)})},[]);function gen(r=rs,c=cs){if(!r.length||!c.length)return;setCh({name:pick(names),race:pick(r).name,cls:pick(c).name,attrs:{Força:attr(),Destreza:attr(),Constituição:attr(),Inteligência:attr(),Sabedoria:attr(),Carisma:attr()}})}return <main className="container gen"><section><h1>Gerador</h1><p>Crie NPCs rápidos com dados vindos da API.</p><button className="btn" onClick={()=>gen()}>Gerar novo</button></section>{ch&&<section className="sheet"><h2>{ch.name}</h2><p>{ch.race} • {ch.cls}</p><div className="attrs">{Object.entries(ch.attrs).map(([k,v])=><div><small>{k}</small><b>{v}</b></div>)}</div></section>}</main>}
function Detail({type}){const{index}=useParams();const[data,setData]=useState(null);useEffect(()=>{req(`/${type}/${index}`).then(setData)},[index,type]);if(!data)return <main className="center">Carregando detalhes...</main>;return <main className="container"><Link className="btn ghost" to="/"><ArrowLeft/>Voltar</Link><section className="sheet"><span>Rota dinâmica: /{type}/{index}</span><h1>{data.name}</h1>{type==='races'?<><p>Velocidade: {data.speed}</p><p>Tamanho: {data.size}</p><p>{data.age}</p></>:<><p>Dado de vida: d{data.hit_die}</p><p>Testes: {data.saving_throws?.map(x=>x.name).join(', ')}</p></>}</section></main>}
function NotFound(){return <main className="center"><h1>404</h1><p>Página não encontrada.</p><Link className="btn" to="/">Voltar</Link></main>}
function App(){return <BrowserRouter><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/gerador" element={<Generator/>}/><Route path="/racas/:index" element={<Detail type="races"/>}/><Route path="/classes/:index" element={<Detail type="classes"/>}/><Route path="*" element={<NotFound/>}/></Routes></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>);
